---
title: "Homework 3"
author: "Su Goh"
date: "25/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2
```{r}
data(stackloss)
plot(stackloss)
mlr_stackloss <- lm (stack.loss ~ Air.Flow + Water.Temp + Acid.Conc. , data = stackloss)
summary(mlr_stackloss)
confint(mlr_stackloss, level = 0.9)
predict(mlr_stackloss, newdata = data.frame(Air.Flow=58, Water.Temp=20, Acid.Conc.=86), interval = "prediction", level = 0.95)
mlr_stackloss_no3 <- lm (stack.loss ~ Air.Flow + Water.Temp , data = stackloss)
anova(mlr_stackloss_no3, mlr_stackloss)
```

## Question 3
### a) Data Plot
```{r}
data(ChickWeight)
coplot(weight ~ Time | Chick, data = ChickWeight, type='b', show.given = FALSE)
coplot(weight ~ Time | Diet, data = ChickWeight, columns=4, show.given = FALSE)
```


### b) Chick 6
```{r}
chick6_data <- ChickWeight[which(ChickWeight$Chick==6), ]
chick6 <- lm(weight ~ Time, data=chick6_data)
plot(weight~Time, data=chick6_data, main='Chick 6 (weight ~ Time)')
abline(chick6)
chick6_poly2 <- lm(weight ~ poly(Time,2, raw=TRUE), data=chick6_data)
chick6_poly3 <- lm(weight ~ poly(Time,3, raw=TRUE), data=chick6_data)
chick6_poly4 <- lm(weight ~ poly(Time,4, raw=TRUE), data=chick6_data)
lines(chick6_data$Time, predict(chick6_poly2), col = 'pink')
lines(chick6_data$Time, predict(chick6_poly3), col = 'orange')
lines(chick6_data$Time, predict(chick6_poly4), col = 'red')
legend(0, 160, legend=c("Linear", "deg=2", "deg=3", "deg=4"),
       col=c("black", "pink", "orange", "red"), lty=1)
plot(residuals(chick6) ~ chick6_data$Time, main='Residuals for linear regression')
plot(residuals(chick6_poly4) ~ chick6_data$Time, main='Residuals for polynomial regression (deg=4)')
summary(chick6_poly4)

```

aksdfsd


### c) ChickWeight (weight ~ Time)
```{r}
plot(weight~Time, data=ChickWeight, main='ChickWeight (weight ~ Time)')
chick_model <- lm(weight ~ Time, data=ChickWeight)
abline(chick_model)
chick_poly <- lm(weight ~ poly(Time, 2), data=ChickWeight)
poly_data <- data.frame(x=ChickWeight$Time, y=predict(chick_poly, data=ChickWeight$Time))
poly_data <- poly_data[order(poly_data$x),]
lines(poly_data$x, poly_data$y, col='red')
plot(residuals(chick_model) ~ ChickWeight$Time, main='Residuals for linear regression')
abline(lm(residuals(chick_model) ~ ChickWeight$Time), col='green')
plot(residuals(chick_poly) ~ ChickWeight$Time, main='Residuals for polynomial regression (deg=2)')
abline(lm(residuals(chick_poly) ~ ChickWeight$Time), col='green')
```


### d) ChickWeight (weight ~ Time), controlling for Diet
```{r}
plot(weight~Time, data=ChickWeight, main='ChickWeight (weight ~ Time)')
colors <- c('blue', 'purple','orchid', 'red')
diet_1 <- ChickWeight[which(ChickWeight$Diet==1),]
diet_2 <- ChickWeight[which(ChickWeight$Diet==2),]
diet_3 <- ChickWeight[which(ChickWeight$Diet==3),]
diet_4 <- ChickWeight[which(ChickWeight$Diet==4),]
model_1 <- lm(weight ~ Time, data=diet_1)
model_2 <- lm(weight ~ Time, data=diet_2)
model_3 <- lm(weight ~ Time, data=diet_3)
model_4 <- lm(weight ~ Time, data=diet_4)
abline(model_1, col=colors[1], lw=2)
abline(model_2, col=colors[2], lw=2)
abline(model_3, col=colors[3], lw=2)
abline(model_4, col=colors[4], lw=2)
legend(0, 380, legend=c("Diet 1", "Diet 2", "Diet 3", "Diet 4"),
       col=colors, lw=2)
boxplot(residuals(model_1), residuals(model_2), residuals(model_3), residuals(model_4), xlab="Diet", ylab='Residuals')
par(mfrow=c(2,2))
plot(residuals(model_1) ~ diet_1$Time, main='Residuals for regression in Diet 1')
abline(lm(residuals(model_1) ~ diet_1$Time), col='green')
plot(residuals(model_2) ~ diet_2$Time, main='Residuals for regression in Diet 2')
abline(lm(residuals(model_2) ~ diet_2$Time), col='green')
plot(residuals(model_3) ~ diet_3$Time, main='Residuals for regression in Diet 3')
abline(lm(residuals(model_3) ~ diet_3$Time), col='green')
plot(residuals(model_4) ~ diet_4$Time, main='Residuals for regression in Diet 4')
abline(lm(residuals(model_4) ~ diet_4$Time), col='green')
```

